[package]
name = "UefiVariablePolicyLibRust"
version = "0.1.0"
authors = ["Bret Barkelew <brbarkel@microsoft.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lib]
name = "UefiVariablePolicyLibRust"
crate-type = ["staticlib"]

[dependencies.r-efi]
git = "https://github.com/microsoft/mu_rust.git"

[dependencies.allocation]
features = ["alloc_by_c"]
git = "https://github.com/microsoft/mu_rust.git"

[dependencies.panic]
git = "https://github.com/microsoft/mu_rust.git"
